apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: "%GRAFANA_ADMIN_USER%"
  admin-password: "%GRAFANA_ADMIN_PASSWORD%"
