apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-api-app
  template:
    metadata:
      labels:
        app: fast-api-app
    spec:
      containers:
        - name: fast-api-app
          image: fast-api-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
            - containerPort: 8000
            - containerPort: 8001
          env:
            - name: ENV
              value: "development"
            - name: RANKINGS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: RANKINGS_DB_NAME
            - name: RANKINGS_DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: RANKINGS_DB_SCHEMA
            - name: API_TOKEN_PEPPER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: API_TOKEN_PEPPER
            - name: ADMIN_TOKEN_PEPPER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: ADMIN_TOKEN_PEPPER
            - name: ADMIN_API_TOKENS_HASHED
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: ADMIN_API_TOKENS_HASHED
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PORT
            - name: COMP_LEADERBOARD_ENABLED
              value: "true"
