apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 8000
    name: http
  - port: 8001
    targetPort: 8001
    name: websocket
  type: NodePort