apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splattop-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: splattop
  source:
    repoURL: https://github.com/cesaregarza/SplatTop
    targetRevision: 4f68cf5a176f89778cf896a84cfb8689093321cd
    path: helm/splattop
    helm:
      releaseName: splattop-prod
      # Use production values override
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  orphanedResources:
    warn: true
    ignore:
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v7
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v8
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v9
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v10
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v11
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v12
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v13
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v14
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v15
      - kind: Secret
        namespace: default
        name: sh.helm.release.v1.splattop-prod.v16
      - group: networking.k8s.io
        kind: Ingress
        namespace: default
        name: dev-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  # Enable health checks for all resources
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
        - /metadata/annotations/argocd.argoproj.io~1tracking-id
