fastApi:
  replicaCount: 1
  image:
    repository: fast-api-app
    tag: latest
    pullPolicy: Never
  imagePullSecrets: []
  env:
    ENV: development
  service:
    name: fast-api-app-service
    type: NodePort
    httpPort: 80
    httpTargetPort: 8000
    websocketPort: 8001
    websocketTargetPort: 8001

react:
  replicaCount: 1
  image:
    repository: react-app
    tag: latest
    pullPolicy: Never
  imagePullSecrets: []
  env:
    ENV: development
    REACT_APP_SHOWCASE_STABLE_LEADERBOARD: "true"
  service:
    name: react-app-service
    type: ClusterIP
    port: 80
    targetPort: 80

celeryWorker:
  image:
    repository: celery-worker
    tag: latest
    pullPolicy: Never
  imagePullSecrets: []

celeryBeat:
  image:
    repository: celery-worker
    tag: latest
    pullPolicy: Never
  imagePullSecrets: []

redis:
  image:
    tag: latest
    pullPolicy: IfNotPresent

splatgpt:
  image:
    repository: splatnlp
    tag: latest
    pullPolicy: Never
  imagePullSecrets: []
  env:
    ENV: development
