apiVersion: v1
kind: Secret
metadata:
    name: splattop-comp-auth-secrets
type: Opaque
stringData:
    COMP_AUTH_ADMIN_DISCORD_IDS: ENC[AES256_GCM,data:aULHnN9aFFXWU8VcbvNjJ4E=,iv:rwL8QpN5lSHFlo1PObS3fdzIxbnWTJYV9zCvzu1lK5M=,tag:kLkEF0bxUBfzf/+qb+GnAQ==,type:str]
    COMP_DISCORD_CLIENT_ID: ENC[AES256_GCM,data:499EyyIZ963rOF6C4rZIaG3C6w==,iv:b//2HULc04VuHIybqtszNgqIAnWdCy7oCxUAGKTOQeQ=,tag:R9q9rtq3fbVgXB2WzvN+6Q==,type:str]
    COMP_DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:tjTdgXgDS8j33kT2MwnkNJYCrvxAODZy/uDia62mHvI=,iv:wNKvNn5FGPyqaHJYN2erTl8DIYs8ujv7L+taTZEnjCg=,tag:yt9mIiqIESiAqU3Wa4lToA==,type:str]
    COMP_DISCORD_REDIRECT_URI: ENC[AES256_GCM,data:ejrzEItTVxCEJN1no1AsgKPm5iOLxxHbdV3Cm2vQTiRlA1pvQsk87+hdO7dtupxe/TfKmQw=,iv:CuBmcWpd+wFVHdQz3dzR2JLXryDd37GEjgK90cuf1B0=,tag:2iAuxqn8DgI8W45kTaFM7A==,type:str]
    COMP_AUTH_SESSION_SECRET: ENC[AES256_GCM,data:ocZPSOBg6sfbESbp4T1MvPcjgWjU7fYBQWttNYH5sqn/S2sDDrOoPWqVzyFYaTIiskrqb4VptmBPWSYdsGCVzQ==,iv:q7FRIGplM00TeLRj8DxxFaevTBDWK7lZh9eGUN1/Cm8=,tag:JVxLmbSiJ/91wE9Kp57hMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yxsawhpecdrhas2q3z246q3tjq8889m552lqhjcgf8jnt7naszqqgz8vt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdWFPdDA2MC9hWFhkcmhN
            V1JrZ3FtNmVTc05lODB5VWFkbjFYTHF3aDJRClMyKzZYT3Fkd0pRZERiYkZCdHVa
            QmRJQ0Q3YUo0SzZ5MDVDZ2cvdzRIYW8KLS0tICtuY2tKeVc5VUFaM2FvKzNXSHNi
            SDFKS3pwS0FveG9MWVF4SVlQaVBFdncKIwVrGBwo8PKYc0Y9U/kLKPn23ghMIMhe
            wwj60aKN8ApXybyji247JXslx4B6No5jucwCp8KDTg3hUI7EhI72/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T07:53:36Z"
    mac: ENC[AES256_GCM,data:kb48yFI/Bhay8QVN78rmgbttZDLyTt5u2FJjv5409IyXi73QGa7szAwY4DsKDWP7z0cE+tsTTLXvzLQqYe4+rGFjqoI2c0iEtKcbgODaUXerMUTxLJkbn1gWuPvwGlAAVJbx5yoZQXZGxdPlQJc2nBq0B1gaTunmfebFxtzSocQ=,iv:zvBomFpXjb/e/N0f1wcOlDG7u5cSpCm/VfN5HWXGJt0=,tag:K2yWJNXBjRl7NJbPExrZ3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
