name: Build and Update discord bot

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/discord-bot
    paths:
      - "src/discord_bot/**"

jobs:
  discord_bot:
    runs-on: ubuntu-latest
    environment: SplatTop
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_SPLATTOP_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install s3cmd
        run: sudo apt-get install s3cmd

      - name: Configure s3cmd to use DigitalOcean Spaces
        run: |
          echo "[default]
          access_key = ${{ secrets.DO_SPACES_KEY }}
          secret_key = ${{ secrets.DO_SPACES_SECRET }}
          host_base = nyc3.digitaloceanspaces.com
          host_bucket = %(bucket)s.nyc3.digitaloceanspaces.com
          use_https = True" > ~/.s3cfg

      - name: Login to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build and push Docker image
        run: |
          docker build \
            -t registry.digitalocean.com/sendouq/discord-bot:latest \
            -f dockerfiles/dockerfile.discord .
          docker push registry.digitalocean.com/sendouq/discord-bot:latest

      - name: Get self IP
        id: self_ip
        run: |
          SELF_IP=$(curl -s https://api.ipify.org)
          echo $SELF_IP
          echo "self_ip=$SELF_IP" >> $GITHUB_OUTPUT

      - name: Terraform Init
        working-directory: terraform/discord
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.DO_SPACES_KEY_DISCORD }}" \
            -backend-config="secret_key=${{ secrets.DO_SPACES_SECRET_DISCORD }}"

      - name: Terraform Plan
        working-directory: terraform/discord
        run: terraform plan -out=tfplan
        env:
          TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          TF_VAR_source_ip: ${{ steps.self_ip.outputs.self_ip }}
          TF_VAR_joy_ip: ${{ secrets.JOY_IP }}
          TF_VAR_database_cluster_name: ${{ secrets.DIGITALOCEAN_DATABASE_CLUSTER }}

      - name: Terraform Apply
        id: terraform_apply
        working-directory: terraform/discord
        run: |
          terraform apply -auto-approve tfplan
          BOT_HOST_IP=$(terraform output -raw bot_host_ip)
          BOT_HOST_ID=$(terraform output -raw bot_host_id)
          echo "bot_host_ip=$BOT_HOST_IP" >> $GITHUB_OUTPUT
          echo "bot_host_id=$BOT_HOST_ID" >> $GITHUB_OUTPUT

      - name: Wait for Droplet to come online
        run: |
          sleep 90

      - name: SSH to Droplet
        id: ssh
        continue-on-error: true
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.terraform_apply.outputs.bot_host_ip }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY_ED }}
          script: |
            export PATH=$PATH:/usr/sbin
            export DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            export DO_API_TOKEN=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            sudo apt-get update
            sudo apt-get install -y docker.io
            docker login -u $DO_API_TOKEN \
              -p $DO_API_TOKEN registry.digitalocean.com/sendouq
            docker pull registry.digitalocean.com/sendouq/discord-bot:latest
            docker run -d --name discord-bot \
              -e DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN \
              --entrypoint poetry \
              registry.digitalocean.com/sendouq/discord-bot:latest \
              run start_discord_bot

      - name: Sleep if droplet is still not ready
        id: resleep
        if: ${{ steps.ssh.outcome == 'failure' }}
        run: |
          sleep 60

      - name: SSH to Droplet
        id: ressh
        if: ${{ steps.ssh.outcome == 'failure' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.terraform_apply.outputs.bot_host_ip }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY_ED }}
          script: |
            export PATH=$PATH:/usr/sbin
            export DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            export DO_API_TOKEN=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            sudo apt-get update
            sudo apt-get install -y docker.io
            docker login -u $DO_API_TOKEN \
              -p $DO_API_TOKEN registry.digitalocean.com/sendouq
            docker pull registry.digitalocean.com/sendouq/discord-bot:latest
            docker run -d --name discord-bot \
              -e DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN \
              --entrypoint poetry \
              registry.digitalocean.com/sendouq/discord-bot:latest \
              run start_discord_bot

      - name: Destroy infrastructure if fail
        if: ${{ failure() && steps.terraform_apply.outcome == 'success' }}
        working-directory: terraform/discord
        run: |
          terraform init
          terraform destroy -auto-approve \
            -var "do_token=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" \
            -var "source_ip=${{ steps.self_ip.outputs.self_ip }}" \
            -var "joy_ip=${{ secrets.JOY_IP }}" \
            -var "database_cluster_name=${{ secrets.DIGITALOCEAN_DATABASE_CLUSTER }}"
